services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "Sa@2026!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - taxservices-network
    volumes:
      - sqlserver-data:/var/opt/mssql

volumes:
  sqlserver-data:
