import { ArrowRight, CheckCircle2 } from 'lucide-react'
import { Link } from 'react-router-dom'
import Navbar from '../../components/Navbar'
import Footer from '../../components/Footer'
import PageHero from '../../components/PageHero'
import './ServiceDetailPage.css'
const details:Record<string,{title:string;text:string;points:string[]}>={
'individual-tax':{title:'Individual Tax Services',text:'Professional support for personal tax matters, with an emphasis on accuracy, organization, and a clear filing experience.',points:['Personal tax preparation support','Review and organization of tax information','Clear explanations of filing requirements','Practical guidance for your situation']},
'business-tax':{title:'Business Tax Services',text:'Tax support for businesses and owners who want their responsibilities handled clearly and kept organized.',points:['Business tax preparation support','Tax information organization','Planning-focused guidance','Support for ongoing tax responsibilities']},
accounting:{title:'Accounting Services',text:'Reliable accounting support that helps you keep financial information organized and easier to understand.',points:['Financial record organization','Accounting support for business operations','Clear financial information','Practical reporting support']},
bookkeeping:{title:'Bookkeeping Services',text:'Consistent bookkeeping that gives you dependable records and a clearer picture of your business finances.',points:['Transaction recording and organization','Account reconciliation support','Ongoing record maintenance','Business-ready financial information']},
'tax-compliance':{title:'Tax Filing & Compliance',text:'Stay organized and confident with professional support for tax filing and compliance responsibilities.',points:['Filing preparation support','Compliance-focused organization','Deadline and document awareness','Clear communication throughout the process']}}
export default function ServiceDetailPage({slug}:{slug:string}){const d=details[slug]??details['individual-tax'];return <><Navbar/><main><PageHero eyebrow="OUR SERVICES" title={d.title} text={d.text}/><section className="service-detail"><div className="section-shell service-detail__layout"><div><div className="section-eyebrow">WHAT WE CAN HELP WITH</div><h2 className="section-title">A straightforward service experience.</h2><p className="section-copy">We focus on keeping the process clear and organized. The exact scope of work can be discussed based on your circumstances and the service you need.</p><div className="service-detail__points">{d.points.map(p=><div key={p} className="service-detail__point"><CheckCircle2 size={20}/><span>{p}</span></div>)}</div></div><div className="service-detail__cta-wrap"><div className="service-detail__cta"><h3>Ready to get started?</h3><p>Tell us what you need and we can discuss the right next step for you.</p><Link to="/contact" className="brand-button service-detail__button">Contact us <ArrowRight size={17}/></Link></div></div></div></section></main><Footer/></>}
